version: 2
project_name: nextgen-go-cli

builds:
  - binary: nextgen-go-cli
    env:
      - CGO_ENABLED=0
    main: ./main.go
    ldflags:
      - "-s -w"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

# Instead of tar.gz, instruct GoReleaser to produce raw binaries:
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: guerrilla-interactive
    name: nextgen-go-cli
