version: 2
project_name: nextgen-go-cli

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    ldflags:
      - "-s -w"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# Configure how GoReleaser will create GitHub releases.
release:
  github:
    owner: guerrilla-interactive
    name: nextgen-go-cli
