version: 2
project_name: nextgen-go-cli

builds:
  - binary: nextgen-go-cli
    env:
      - CGO_ENABLED=0
    main: ./main.go
    ldflags:
      - "-s -w"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

release:
  github:
    owner: guerrilla-interactive
    name: nextgen-go-cli
