name: Auto-Tag on package.json Version Change

on:
  push:
    branches:
      - main
    # Only run if package.json changes, so we only tag on a version bump
    paths:
      - "package.json"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Ensure we have the full commit history so we can tag properly.

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Read version from package.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "PACKAGE_VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and push git tag
        run: |
          TAG="v${{ steps.read_version.outputs.PACKAGE_VERSION }}"
          echo "Creating git tag $TAG for commit $GITHUB_SHA"
          git tag -a "$TAG" "$GITHUB_SHA" -m "Auto-tag $TAG"
          git push origin "$TAG" 