name: Build and Publish with GoReleaser

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Dist Directory
        run: |
          echo "Checking dist/ directory..."
          ls -l dist || echo "dist/ directory not found!"

      - name: Copy Built Binaries
        run: |
          echo "Copying binaries to bin/..."
          if [ -d "dist" ]; then
            cp dist/nextgen-go-cli_linux_amd64 bin/cli-linux || echo "Linux binary missing!"
            cp dist/nextgen-go-cli_darwin_amd64 bin/cli-macos || echo "MacOS binary missing!"
            cp dist/nextgen-go-cli_windows_amd64.exe bin/cli-win.exe || echo "Windows binary missing!"
          else
            echo "dist/ directory does not exist."
            exit 1
          fi

      - name: Install Dependencies
        run: npm install

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
