name: Build and Publish with GoReleaser

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Binaries
        run: |
          echo "Copying built binaries to bin/..."
          rm -f bin/cli-linux || true
          rm -f bin/cli-macos || true
          rm -f bin/cli-win.exe || true

          cp dist/nextgen-go-cli_linux_amd64_v1/nextgen-go-cli bin/cli-linux || echo "No Linux binary found."
          cp dist/nextgen-go-cli_darwin_amd64_v1/nextgen-go-cli bin/cli-macos || echo "No macOS binary found."
          cp dist/nextgen-go-cli_windows_amd64_v1/nextgen-go-cli.exe bin/cli-win.exe || echo "No Windows binary found."

          chmod +x bin/cli-linux || true
          chmod +x bin/cli-macos || true
          chmod +x bin/cli-win.exe || true

          echo "Done copying binaries."

  publish-npm:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Optionally install to ensure dependencies are present if needed
      - name: Install Dependencies
        run: npm install

      # Explicitly run the build-binaries script (if not already done in 'release' job)
      - name: Build Binaries
        run: npm run build-binaries

      # Check what's in bin and dist
      - name: Debug
        run: |
          echo "Contents of bin/:"
          ls -l bin
          echo "Contents of dist/:"
          ls -l dist

      - name: Publish
        run: npm publish
