name: Build and Publish with GoReleaser

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install
      
      # If you want to copy GoReleaser's artifacts:
      - name: Copy Built Binaries
        run: |
          # Example: if the artifacts are placed in dist/ from GoReleaser
          cp dist/nextgen-go-cli_linux_amd64/nextgen-go-cli bin/cli-linux
          cp dist/nextgen-go-cli_darwin_amd64/nextgen-go-cli bin/cli-macos
          cp dist/nextgen-go-cli_windows_amd64/nextgen-go-cli.exe bin/cli-win.exe
      
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
